--- #YAML:1.0
name:               Microarray-GEO-SOFT
version:            0.10
abstract:           Reading microarray data in SOFT format from GEO database
author:
    - Zuguang Gu <jokergoo@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Basename:       
    List::Vectorize:      
    LWP::UserAgent:       
    Microarray::ExprSet:  
    Test::More:           
    Thread:               
    threads::shared:      
    Time::HiRes:          
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
